---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Preface {.unnumbered}

This document uses the IUCN Red List of Ecosystems guidelines to diagnose the collapse of the **Tropical glacier ecosystems of the Cordillera de Mérida** in Venezuela.

Tropical glaciers are rapidly disappearing, particularly in isolated mountain peaks and lower elevations (below 5000m). These glaciers are fundamental substrates for unique cryogenic ecosystems in tropical environments where the ice, melting water and rocky substrate sustain microbiological communities and other meso- and macro-biota. 

The [IUCN Red List of Ecosystems](https://iucnrle.org) assessment protocol provides a valuable framework for comparative analysis of threatened ecosystems. We undertook the assessment with existing data derived from field observations and samples, literature review, cartographic reconstruction, remote sensing products and climatic models, and complemented these with additional statistical analysis and modelling to calculate and predict rates of decline and relative severity of degradation. 

The evidence suggests an extreme risk of collapse ([Critically Endangered](https://iucnrle.org/rle-categ-and-criteria),   <span style="padding: 2px; font-size:80%; border-radius: 22px; color: white; background-color: #ff0000; " id="text">CR</span>) due to prolonged and acute declines in ice extent and changes in climatic conditions that are leading towards a complete loss of ice mass. The biotic compartments of the glacial ecosystem will consequently be lost, with ice loss also initiating a decades-long succession of forefield vegetation. Even the most optimistic climate change projections are unlikely to prevent imminent ecosystem collapse in this region. 

This assessment is summarised in a manuscript currently in press [@FerrerParis_Glacier_Merida_2023].

## External links

The html version of this report is available in GitHub pages:
<https://red-list-ecosystem.github.io/T6.1-SA-01-VE-01-Cordillera-Merida/>

A PDF version of this assessment report has been uploaded to EcoEvoRxiv, and is available under the DOI [10.32942/X2VK54](https://doi.org/10.32942/X2VK54).

Reproducible code and data are available as an OSF project with DOI [10.17605/OSF.IO/Y3279](https://doi.org/10.17605/OSF.IO/Y3279)



