---
title: "IUCN Red List of Ecosystem assessment: Tropical glacier ecosystem of the Cordillera de Mérida"
subtitle: "Supplementary material to: First Red List of Ecosystems assessment of a tropical glacier ecosystem to diagnose the pathways toward imminent collapse"
authors: 
  - name: "J. R. Ferrer-Paris"
    email: j.ferrer@unsw.edu.au
    orcid: 0000-0002-9554-3395
    corresponding: true
    affiliations:
      - id: ces
        name: Centre for Ecosystem Science, University of New South Wales
        city: Sydney
        country: Australia
      - id: udash
        name: UNSW Data Science Hub, University of New South Wales
        city: Sydney
        country: Australia
      - id: iucn
        name: IUCN Commission on Ecosystem Management
        city: Gland
        country: Switzerland 
  - name: "Luis D. Llambí"
    orcid: 0000-0002-2031-810X
    affiliations:
      - name: Instituto de Ciencias Ambientales y Ecológicas, Universidad de Los Andes
        city: Mérida
        country: Venezuela 
      - name: Consorcio para el Desarrollo Sostenible de la Ecoregión Andina (CONDESAN)
        city: Quito
        country: Ecuador
  - name: " Alejandra Melfo"
    orcid: 0000-0003-3673-4308
    affiliations:
      - name: Centro de Física Fundamental, Universidad de Los Andes
        city: Mérida
        country: Venezuela
  - name: "David A. Keith"
    orcid: 0000-0002-7627-4150
    affiliations:
      - ref: ces
      - ref: iucn

date: "2023-10-06"

bibliography: 
  - ../bibTeX/references.bib
  - ../bibTeX/glacier-assessments.bib
  - ../bibTeX/additional-refs.bib
  - ../bibTeX/r-packages.bib
  - ../bibTeX/reviewer-suggested.bib
csl: ../bibTeX/oryx.csl

execute:
  echo: false

format:
  RLEpdf-pdf
---

# Abstract

The _Tropical glacier ecosystem of the Cordillera de Mérida_ is a regional ecosystem subgroup (level 4 unit of the IUCN Global Ecosystem Typology) restricted to the Cordillera de Mérida in Venezuela. It included at least five occurrences of glaciers or ice patches in the Sierra Nevada de Mérida and one in the Sierra de Santo Domingo but is currently represented by a single ice mass in the former range. Alpha- Beta- and Gamma-proteobacteria, Actinobacteria and Flavobacteria from glacial and subglacial samples are abundant, morphologically diverse and active. Studies of the microbiota in other ecological zones are still underway or pending. Recently exposed areas of the glacier forefield show strong dominance of lichenized fungi and bryophytes with very few vascular plants. 

The tropical glacier ecosystem of the Cordillera de Mérida had a mapped extent of less than 6 $\mathrm{km}^2$ in 2000 and glacier ice extent was less than 0.5 $\mathrm{km}^2$ in 2019 and is threatened primarily by climate change and air pollution, with recent acceleration of ice loss due to edge and scale effects. The ecosystem is thought to have undergone continuing declines since the second half of the 19th century. Today the ecosystem covers less than 1% of the estimated historical extent. Net area loss since in the last 20 years is about 90% and observed acceleration of the rate of decline suggests it will likely disappear in the next five years. The estimated increases in equilibrium-line altitude between 1820 and 2006 correspond with a best estimate of 70% of relative severity of historical degradation in environmental conditions. Similarly, the increase in freeze level height between 1948 and 2011 indicate more than 80% of averaged relative severity in the last 50 years. Under a wide range of climate change models and shared socio-economic pathways the relative severity of the degradation in suitability of bioclimatic conditions is estimated to reach 97% between 2040 and 2070 and conservative ice mass balance models predict complete loss of ice before 2070 in 79.2% of the simulations. 

Overall, the status of the tropical glacier ecosystem of the Cordillera de Mérida is assessed as **[Critically Endangered](https://iucnrle.org/rle-categ-and-criteria)** with plausible evidence that it may already be **Collapsed**: **CR (CR-CO)**. 

{{< include ../assessment/intro.qmd >}}
{{< include ../assessment/distribution.qmd >}}
{{< include ../assessment/biota.qmd >}}
{{< include ../assessment/abiotic.qmd >}}
{{< include ../assessment/processes.qmd >}}
{{< include ../assessment/collapse.qmd >}}
{{< include ../assessment/risk-assessment.qmd >}}

# Acknowledgements

We thank Nerio Ramírez for his invaluable work documenting glacier retreat and Barbara Huber for kindly sharing preliminary results on glacier microbiota in the Venezuelan Andes. National Geographic Society provided financial support for LDL and AM (Grant No. NGS-55170R-19). We also thank the Mucumbarila cable car system and INPARQUES for their support in the access to the study sites near Humboldt peak.

# Citation

This report is uploaded in EcoEvoRxiv as manuscript number:

This report was produced as a complement to a manuscript under review. Citation information will be updated upon journal decision.

# Linked documents and data

The data and code that support the findings of this study are openly available in OSF at https://osf.io/y3279/.

# References

::: {#refs}
:::

# Version control

| Date | Version | Info |
|---|---|---|
| 2023-06-08 | v1.0 | First version attached to submitted manuscript |
| 2023-10-05 | v2.0 | Second version, including suggestions from two anonymous reviewers |
| 2023-10-06 | v2.1 | Include author affiliations and fix errors in figures and tables |