project:
  type: book
  output-dir: _output
  

book:
  title: "IUCN Red List of Ecosystem assessment: Tropical glacier ecosystem of the Cordillera de Mérida"
  subtitle: "Supplementary material to: First Red List of Ecosystems assessment of a tropical glacier ecosystem to diagnose the pathways toward imminent collapse"
  author: 
    - "José R. Ferrer-Paris"
    - "Luis D. Llambí"
    - "Alejandra Melfo" 
    - "David A. Keith"
  date: "2023-05-03"
  chapters:
    - index.qmd
    - ../assessment/intro.qmd
    - ../assessment/distribution.qmd
    - ../assessment/biota.qmd
    - ../assessment/abiotic.qmd
    - ../assessment/processes.qmd
    - ../assessment/collapse.qmd
    - ../assessment/risk-assessment.qmd
    - ../references.qmd

number-depth: 2
top-level-division: section
bibliography: 
  - ../bibTeX/references.bib
  - ../bibTeX/glacier-assessments.bib
  - ../bibTeX/additional-refs.bib
csl: ../bibTeX/oryx.csl
toc-depth: 2

execute:
  echo: false

format:
  pdf: 
    documentclass: scrartcl
    fontfamily: libertinus

  