---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Characteristic biota

Tropical glacier ecosystems have five main ecological zones [@Hotaling_2017_glacier_ecosystem]: the supraglacial surfaces, englacial interior, subglacial bedrock–ice interface, proglacial streams and lakes and glacier forefields. The few available ecological studies on the Cordillera de Mérida have focused on some elements of the supraglacial and subglacial surfaces and the vegetation succession in the glacier forefield, while sediments and pollen of proglacial lakes have been studied to reconstruct paleoclimates and do not provide information on their biota  [@Polissar_2006_IceAge_Andes;@Stansell_2014_ProglacialLakes_Merida]. 

## Supraglacial and subglacial surfaces

### Microbiota
Bacteria have been isolated and characterised from glacial and subglacial samples from the Humboldt glacier [@Ball_2014_biota_merida;@Balcazar_2015_biota_merida] and the Bolívar glacier [@Rondon_2016_biota_merida]. These prospective studies found abundant, morphologically diverse and active bacterial cells, including very small or "dwarf cells". Isolates were grouped in five different phyla/classes (Alpha-, Beta- and Gamma-[proteobacteria](https://en.wikipedia.org/wiki/Pseudomonadota), [Actinobacteria](https://en.wikipedia.org/wiki/Actinomycetota) and [Flavobacteria](https://en.wikipedia.org/wiki/Flavobacteriia)), many were psychrophilic or psychrotolerant and there was evidence of metal resistance and excreted cold-active extracellular proteases and amylases.

### Meio- and macrobiota

Glacier-mice ([Moss balls](https://en.wikipedia.org/wiki/Glacier_mice)) have been studied in high mountain areas with páramo vegetation in the Cordillera de Mérida [@Perez_1991_biota_merida] but there are no published records of their presence in former or current glacier areas. 

@Edwards_1987_nival_arthropods mentions a nival entomofauna of at least two species of carabids and several anyphaenid, salticid and erigonid spiders that depend on arthropod fallout in the surroundings of Pico Espejo and Pico Bolívar.

## Glacier forefield

### Microbiota

Data collected at Humboldt peak in 2019 and 2021 (including supraglacial, endoglacial and subglacial samples, as well as soil forom the glacial forefront) may shed light on the connections between components of the ecosystem. Analysis is still underway (Huber et al. in prep.), with preliminary results indicating a large diversity, marked changes in microbiota composition and function, and a sizeable role of the microbiota on ecosystem processes in four sites deglaciated between 1910 and 2009. 


### Macrobiota

@Llambi_2021_periglacial_merida studied the soil development and vegetation assembly in a chronosequence of four sites where the Humboldt glacier retreated between 1910 and 2009. [Biological soil crusts](https://en.wikipedia.org/wiki/Biological_soil_crust) (BSCs) are present near the borders of the receding glacier of peak Humboldt, but there was no significant interaction between time and BSC presence or between BSCs and soil properties. Soil organic matter and soil nitrogen increases progressively during the succession while some exchangeable bases (magnesium and calcium) decreased in sites older than 21 years.

The areas exposed in the last 10 years show a strong dominance of lichenized fungi (families [Hymeneliaceae](https://en.wikipedia.org/wiki/Hymeneliaceae), Peltigeraceae, [Stereocaulaceae](https://en.wikipedia.org/wiki/Stereocaulaceae), and Trapeliaceae) and bryophytes ([Andreaeaceae](https://en.wikipedia.org/wiki/Andreaeaceae), Bryaceaea, Cephaloziellaceae, Dicranaceae, Grimmiaceae, [Polytrichaceae](https://en.wikipedia.org/wiki/Polytrichaceae), [Pottiaceae](https://en.wikipedia.org/wiki/Pottiaceae)) with very few vascular plants.  Vascular plant cover remained low during the first six decades, and was almost exclusively represented by wind dispersed/pollinated grasses.
